spring.application.name=imagic-spring-aws

spring.cloud.aws.endpoint=https://hb.ru-msk.vkcloud-storage.ru
spring.cloud.aws.region.static=ru-msk
spring.cloud.aws.credentials.access-key=dbncoKwkdfF3rAJ47Kpshi
spring.cloud.aws.credentials.secret-key=6z5d3aLq13DEfAWkqcBK7GuS2H4ihnvok3NkwmJnPiPU
bucket-name=imagic