spring.application.name=imagic-spring-aws
external.api.url=https://smarty.mail.ru
external.api.key=SQjvDiJTnZ3MBAgcQk6rfMWjUcfNsnHjPA9qLwSjB4BS3SESo
cv.meta-info={"mode": ["pedestrian"],"images": [{"name": "file"}]}
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
server.port=8083