spring.application.name=imagic-spring-aws
external.api.url=https://smarty.mail.ru
external.api.key=68ANgvsnSdthgqxdqEs5q95krcM5UPUW4eHN7sv9B24FgGSZqTgUJDfEbc3w7s
cv.meta-info={"mode": ["object2"],"images": [{"name": "file"}]}