apiVersion: apps/v1
kind: Deployment
metadata:
  name: imagic

spec:
  replicas: 1
  selector:
    matchLabels:
      app: imagic
  template:
    metadata:
      labels:
        app: imagic
    spec:
      containers:
        - name: imagic
          image: rruslek/imagic-spring
          ports:
            - containerPort: 8080