services:
  app:
    image: 'sneakershopa:latest'
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8181:8181"
    depends_on:
      - db
    environment:
      - SERVER_PORT= 8181
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/sneakershop
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=870125
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
    image: 'postgres:17.0'
    container_name: db
    environment:
      - POSTGRES_DB=sneakershop
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=870125
    volumes:
      - ./create_db.sql:/docker-entrypoint-initdb.d/create_db.sql
      - db-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  db-data: