spring.application.name=imagic-spring-aws

spring.cloud.aws.endpoint=https://hb.ru-msk.vkcloud-storage.ru
spring.cloud.aws.region.static=ru-msk
spring.cloud.aws.credentials.access-key=5c92PnxCi5eXY225X58FCU
spring.cloud.aws.credentials.secret-key=bFZ7ESuUnSWST1DiSg1Q6TpN418HC6cowc2gMjExgksL
bucket-name=imagic
server.port=8082